### ISSUE TITLE
对面影魔完全不出现

### ISSUE THREAD

**Issue by Hill-Jiang** [bilibili/LastOrder-Dota2#4]
参照教程配置试了一下，对面影魔完全不出现

启动 DOTA2 进入房间后 powershell 有报错，从启动开始的全部打印如下：
```
PS C:\Users\Hill\Documents\Github\LastOrder-Dota2-main> python38 .\play_with_human_local.py
2021-08-05 22:53:24.303362: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-05 22:53:24.303518: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-05 22:53:26,781 WARNING  From C:\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
C:\Users\Hill\Documents\Github\LastOrder-Dota2-main
C:\Users\Hill\Documents\Github\LastOrder-Dota2-main
错误: 没有找到进程 "dota2.exe"。
错误: 没有找到进程 "dota2.exe"。
2021-08-05 22:53:27,323 INFO     D:\Steam\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe -botworldstatesocket_threaded -botworldstatetosocket_frames 6 -botworldstatetosocket_radiant 12120 -botworldstatetosocket_dire 12121 -con_logfile C:\Users\Hill\Documents\Github\LastOrder-Dota2-main\bots\console.log -con_timestamp -console -insecure -noip -nowatchdog +clientport 27006 +dota_surrender_on_disconnect 0 +host_timescale 1 +hostname dotaservice +sv_cheats 1 +sv_hibernate_when_empty 0 +tv_delay 0 +tv_enable 1 +tv_title e4066ee7-f5fc-11eb-95d7-001a7dda7111 +tv_autorecord 1 +tv_transmitall 1 +dota_1v1_skip_strategy 1 -novid +sv_lan 0
2021-08-05 22:53:37.981427: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-05 22:53:37.981530: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-05 22:53:41,025 WARNING  From C:\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
C:\Users\Hill\Documents\Github\LastOrder-Dota2-main
2021-08-05 22:53:41,186 WARNING  From C:\Users\Hill\Documents\Github\LastOrder-Dota2-main\model\basic_model.py:125: dense (from tensorflow.python.keras.legacy_tf_layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
2021-08-05 22:53:41,192 WARNING  From C:\Python38\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
2021-08-05 22:53:42.959994: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-08-05 22:53:42.960082: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-05 22:53:42.967498: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-DVE82KF
2021-08-05 22:53:42.967754: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-DVE82KF
2021-08-05 22:53:42.976402: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-05 22:53:42.985048: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1c87ee8d2f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-08-05 22:53:42.985115: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
count_parameters: 4108912 {'creep_block/feature_global_tran/dense/kernel:0': 225, 'creep_block/feature_global_tran/dense/bias:0': 15, 'creep_block/feature_global_tran/feature_global_tran_ln/norm_gain:0': 15, 'creep_block/feature_global_tran/feature_global_tran_ln/norm_bias:0': 15, 'creep_block/feature_unit_global_tran_1/dense/kernel:0': 7200, 'creep_block/feature_unit_global_tran_1/dense/bias:0': 200, 'creep_block/feature_unit_global_tran_1/feature_unit_global_tran_1_ln/norm_gain:0': 200, 'creep_block/feature_unit_global_tran_1/feature_unit_global_tran_1_ln/norm_bias:0': 200, 'creep_block/self_hero_feature_raw/dense/kernel:0': 16000, 'creep_block/self_hero_feature_raw/dense/bias:0': 80, 'creep_block/self_hero_feature_raw/self_hero_feature_raw_ln/norm_gain:0': 80, 'creep_block/self_hero_feature_raw/self_hero_feature_raw_ln/norm_bias:0': 80, 'creep_block/self_attention/self_attention_fc1/dense/kernel:0': 9000, 'creep_block/self_attention/self_attention_fc1/dense/bias:0': 45, 'creep_block/self_attention/self_attention_fc1/self_attention_fc1_ln/norm_gain:0': 45, 'creep_block/self_attention/self_attention_fc1/self_attention_fc1_ln/norm_bias:0': 45, 'creep_block/self_attention/self_attention_fc2/dense/kernel:0': 3600, 'creep_block/self_attention/self_attention_fc2/dense/bias:0': 80, 'creep_block/self_attention/self_attention_fc2/self_attention_fc2_ln/norm_gain:0': 80, 'creep_block/self_attention/self_attention_fc2/self_attention_fc2_ln/norm_bias:0': 80, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_query_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_query_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_key_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_key_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_value_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_1/self_attention_attention_1_value_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_query_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_query_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_key_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_key_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_value_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_2/self_attention_attention_2_value_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_query_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_query_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_key_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_key_layer/dense/bias:0': 25, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_value_layer/dense/kernel:0': 2000, 'creep_block/self_attention/self_attention_attention_3/self_attention_attention_3_value_layer/dense/bias:0': 25, 'creep_block/feature_concat_raw/dense/kernel:0': 17000, 'creep_block/feature_concat_raw/dense/bias:0': 100, 'creep_block/feature_concat_raw/feature_concat_raw_ln/norm_gain:0': 100, 'creep_block/feature_concat_raw/feature_concat_raw_ln/norm_bias:0': 100, 'creep_block/head_move_degree_fc1/dense/kernel:0': 7500, 'creep_block/head_move_degree_fc1/dense/bias:0': 75, 'creep_block/head_move_degree_fc1/head_move_degree_fc1_ln/norm_gain:0': 75, 'creep_block/head_move_degree_fc1/head_move_degree_fc1_ln/norm_bias:0': 75, 'creep_block/head_move_degree/head_move_degree/dense/kernel:0': 975, 'creep_block/head_move_degree/head_move_degree/dense/bias:0': 13, 'creep_block/state_value_fc1/dense/kernel:0': 7500, 'creep_block/state_value_fc1/dense/bias:0': 75, 'creep_block/state_value_fc1/state_value_fc1_ln/norm_gain:0': 75, 'creep_block/state_value_fc1/state_value_fc1_ln/norm_bias:0': 75, 'creep_block/state_value_fc2/dense/kernel:0': 3750, 'creep_block/state_value_fc2/dense/bias:0': 50, 'creep_block/state_value_fc2/state_value_fc2_ln/norm_gain:0': 50, 'creep_block/state_value_fc2/state_value_fc2_ln/norm_bias:0': 50, 'creep_block/state_value_head/dense/kernel:0': 50, 'creep_block/state_value_head/dense/bias:0': 1, 'all_shared_part/action_type_embedding_matrix:0': 320, 'all_shared_part/move_direction_embedding_matrix:0': 592, 'all_shared_part/enemy_action_type_embedding_matrix:0': 320, 'all_shared_part/enemy_anim_type_embedding_matrix:0': 320, 'all_shared_part/self_anim_type_embedding_matrix:0': 320, 'all_shared_part/feature_unit_global_tran_1/dense/kernel:0': 107600, 'all_shared_part/feature_unit_global_tran_1/dense/bias:0': 200, 'all_shared_part/feature_unit_global_tran_1/feature_unit_global_tran_1_ln/norm_gain:0': 200, 'all_shared_part/feature_unit_global_tran_1/feature_unit_global_tran_1_ln/norm_bias:0': 200, 'all_shared_part/feature_unit_global_tran_2/dense/kernel:0': 20000, 'all_shared_part/feature_unit_global_tran_2/dense/bias:0': 100, 'all_shared_part/feature_unit_global_tran_2/feature_unit_global_tran_2_ln/norm_gain:0': 100, 'all_shared_part/feature_unit_global_tran_2/feature_unit_global_tran_2_ln/norm_bias:0': 100, 'all_shared_part/self_hero_feature_raw/dense/kernel:0': 8000, 'all_shared_part/self_hero_feature_raw/dense/bias:0': 80, 'all_shared_part/self_hero_feature_raw/self_hero_feature_raw_ln/norm_gain:0': 80, 'all_shared_part/self_hero_feature_raw/self_hero_feature_raw_ln/norm_bias:0': 80, 'all_shared_part/enemy_hero_feature_raw/dense/kernel:0': 8000, 'all_shared_part/enemy_hero_feature_raw/dense/bias:0': 80, 'all_shared_part/enemy_hero_feature_raw/enemy_hero_feature_raw_ln/norm_gain:0': 80, 'all_shared_part/enemy_hero_feature_raw/enemy_hero_feature_raw_ln/norm_bias:0': 80, 'all_shared_part/self_tower_feature_raw/dense/kernel:0': 8000, 'all_shared_part/self_tower_feature_raw/dense/bias:0': 80, 'all_shared_part/self_tower_feature_raw/self_tower_feature_raw_ln/norm_gain:0': 80, 'all_shared_part/self_tower_feature_raw/self_tower_feature_raw_ln/norm_bias:0': 80, 'all_shared_part/enemy_tower_feature_raw/dense/kernel:0': 8000, 'all_shared_part/enemy_tower_feature_raw/dense/bias:0': 80, 'all_shared_part/enemy_tower_feature_raw/enemy_tower_feature_raw_ln/norm_gain:0': 80, 'all_shared_part/enemy_tower_feature_raw/enemy_tower_feature_raw_ln/norm_bias:0': 80, 'all_shared_part/enemy_attention/enemy_attention_fc1/dense/kernel:0': 9000, 'all_shared_part/enemy_attention/enemy_attention_fc1/dense/bias:0': 90, 'all_shared_part/enemy_attention/enemy_attention_fc1/enemy_attention_fc1_ln/norm_gain:0': 90, 'all_shared_part/enemy_attention/enemy_attention_fc1/enemy_attention_fc1_ln/norm_bias:0': 90, 'all_shared_part/enemy_attention/enemy_attention_fc2/dense/kernel:0': 7200, 'all_shared_part/enemy_attention/enemy_attention_fc2/dense/bias:0': 80, 'all_shared_part/enemy_attention/enemy_attention_fc2/enemy_attention_fc2_ln/norm_gain:0': 80, 'all_shared_part/enemy_attention/enemy_attention_fc2/enemy_attention_fc2_ln/norm_bias:0': 80, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_query_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_query_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_key_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_key_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_value_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_1/enemy_attention_attention_1_value_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_query_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_query_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_key_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_key_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_value_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_2/enemy_attention_attention_2_value_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_query_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_query_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_key_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_key_layer/dense/bias:0': 50, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_value_layer/dense/kernel:0': 4000, 'all_shared_part/enemy_attention/enemy_attention_attention_3/enemy_attention_attention_3_value_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_fc1/dense/kernel:0': 9000, 'all_shared_part/self_attention/self_attention_fc1/dense/bias:0': 90, 'all_shared_part/self_attention/self_attention_fc1/self_attention_fc1_ln/norm_gain:0': 90, 'all_shared_part/self_attention/self_attention_fc1/self_attention_fc1_ln/norm_bias:0': 90, 'all_shared_part/self_attention/self_attention_fc2/dense/kernel:0': 7200, 'all_shared_part/self_attention/self_attention_fc2/dense/bias:0': 80, 'all_shared_part/self_attention/self_attention_fc2/self_attention_fc2_ln/norm_gain:0': 80, 'all_shared_part/self_attention/self_attention_fc2/self_attention_fc2_ln/norm_bias:0': 80, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_query_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_query_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_key_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_key_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_value_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_1/self_attention_attention_1_value_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_query_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_query_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_key_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_key_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_value_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_2/self_attention_attention_2_value_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_query_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_query_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_key_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_key_layer/dense/bias:0': 50, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_value_layer/dense/kernel:0': 4000, 'all_shared_part/self_attention/self_attention_attention_3/self_attention_attention_3_value_layer/dense/bias:0': 50, 'all_shared_part/cnn_dota_map/conv_c1/w:0': 432, 'all_shared_part/cnn_dota_map/conv_c1/b:0': 8, 'all_shared_part/cnn_dota_map/conv_c2/w:0': 1152, 'all_shared_part/cnn_dota_map/conv_c2/b:0': 16, 'all_shared_part/cnn_dota_map/dota_map_fc/dense/kernel:0': 12800, 'all_shared_part/cnn_dota_map/dota_map_fc/dense/bias:0': 32, 'all_shared_part/cnn_dota_map/dota_map_fc/dota_map_fc_ln/norm_gain:0': 32, 'all_shared_part/cnn_dota_map/dota_map_fc/dota_map_fc_ln/norm_bias:0': 32, 'all_shared_part/feature_global/dense/kernel:0': 8000, 'all_shared_part/feature_global/dense/bias:0': 100, 'all_shared_part/feature_global/feature_global_ln/norm_gain:0': 100, 'all_shared_part/feature_global/feature_global_ln/norm_bias:0': 100, 'all_shared_part/units_lstm/wx:0': 1664000, 'all_shared_part/units_lstm/wh:0': 1000000, 'all_shared_part/units_lstm/b:0': 2000, 'selected_action_head/selected_action_head_1/dense/kernel:0': 150000, 'selected_action_head/selected_action_head_1/dense/bias:0': 300, 'selected_action_head/selected_action_head_1/selected_action_head_1_ln/norm_gain:0': 300, 'selected_action_head/selected_action_head_1/selected_action_head_1_ln/norm_bias:0': 300, 'selected_action_head/selected_action_head_2/dense/kernel:0': 30000, 'selected_action_head/selected_action_head_2/dense/bias:0': 100, 'selected_action_head/selected_action_head_2/selected_action_head_2_ln/norm_gain:0': 100, 'selected_action_head/selected_action_head_2/selected_action_head_2_ln/norm_bias:0': 100, 'selected_action_head/selected_action_head/dense/kernel:0': 2000, 'selected_action_head/selected_action_head/dense/bias:0': 20, 'move_degree_head/head_move_degree_fc1/dense/kernel:0': 150000, 'move_degree_head/head_move_degree_fc1/dense/bias:0': 300, 'move_degree_head/head_move_degree_fc1/head_move_degree_fc1_ln/norm_gain:0': 300, 'move_degree_head/head_move_degree_fc1/head_move_degree_fc1_ln/norm_bias:0': 300, 'move_degree_head/head_move_degree/head_move_degree/dense/kernel:0': 10800, 'move_degree_head/head_move_degree/head_move_degree/dense/bias:0': 36, 'enemy_target_head/enemy_target_fc_out/dense/kernel:0': 150000, 'enemy_target_head/enemy_target_fc_out/dense/bias:0': 300, 'enemy_target_head/enemy_target_fc_out/enemy_target_fc_out_ln/norm_gain:0': 300, 'enemy_target_head/enemy_target_fc_out/enemy_target_fc_out_ln/norm_bias:0': 300, 'enemy_target_head/enemy_target_attention/enemy_target_attention_query_layer/dense/kernel:0': 90000, 'enemy_target_head/enemy_target_attention/enemy_target_attention_query_layer/dense/bias:0': 300, 'enemy_target_head/enemy_target_attention/enemy_target_attention_key_layer/dense/kernel:0': 24000, 'enemy_target_head/enemy_target_attention/enemy_target_attention_key_layer/dense/bias:0': 300, 'self_target_head/self_target_fc_out/dense/kernel:0': 150000, 'self_target_head/self_target_fc_out/dense/bias:0': 300, 'self_target_head/self_target_fc_out/self_target_fc_out_ln/norm_gain:0': 300, 'self_target_head/self_target_fc_out/self_target_fc_out_ln/norm_bias:0': 300, 'self_target_head/self_target_attention/self_target_attention_query_layer/dense/kernel:0': 90000, 'self_target_head/self_target_attention/self_target_attention_query_layer/dense/bias:0': 300, 'self_target_head/self_target_attention/self_target_attention_key_layer/dense/kernel:0': 24000, 'self_target_head/self_target_attention/self_target_attention_key_layer/dense/bias:0': 300, 'state_value_head/state_value_fc1/dense/kernel:0': 150000, 'state_value_head/state_value_fc1/dense/bias:0': 300, 'state_value_head/state_value_fc1/state_value_fc1_ln/norm_gain:0': 300, 'state_value_head/state_value_fc1/state_value_fc1_ln/norm_bias:0': 300, 'state_value_head/state_value_fc2/dense/kernel:0': 30000, 'state_value_head/state_value_fc2/dense/bias:0': 100, 'state_value_head/state_value_fc2/state_value_fc2_ln/norm_gain:0': 100, 'state_value_head/state_value_fc2/state_value_fc2_ln/norm_bias:0': 100, 'state_value_head/state_value_head/dense/kernel:0': 100, 'state_value_head/state_value_head/dense/bias:0': 1}
2021-08-05 22:53:49.211507: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-05 22:53:49.211628: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-05 22:53:52,408 WARNING  From C:\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
C:\Users\Hill\Documents\Github\LastOrder-Dota2-main
Process Process-2:1:
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hill\Documents\Github\LastOrder-Dota2-main\dotaservice\net_console_util.py", line 49, in monitor_log
    line = f.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 4159: illegal multibyte sequence
```

是否与显卡有关，我的是 AMD RX590

**Comment by a04512** [comment]
net_console_util.py里29行
改成这样with open(abs_glob, 'r',encoding="UTF-8") as f:

**Comment by Hill-Jiang** [comment]
> net_console_util.py里29行
> 改成这样with open(abs_glob, 'r',encoding="UTF-8") as f:

谢谢，解决了！

**Comment by Passerby** [comment]
你用了中文名称吧，steam改成英文名

**Comment by Hill-Jiang** [comment]
> 你用了中文名称吧，steam改成英文名

是的，我后来注意到了这个问题，但是我把 Steam 改成英文名后，创建房间的房主显示还是原来的中文名称（可能是 Steam 有延迟），导致仍然出现一样的问题

我把名称再改回中文，按照上述办法修改编码方式，也能正常运行，所以应该是可以支持中文名称的

**Comment by LiuShuai26** [comment]
已更新使用encoding
