### ISSUE TITLE
报错求助

### ISSUE THREAD

**Issue by liuhe19940107** [bilibili/LastOrder-Dota2#6]
PS C:\Users\1060> CD E:\LastOrder-Dota2-main
PS E:\LastOrder-Dota2-main> python .\play_with_human_local.py
2021-08-06 14:30:53.779862: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-06 14:30:53.780524: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-06 14:30:57,613 WARNING  From C:\Users\1060\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File ".\play_with_human_local.py", line 3, in <module>
    from agents.dota_agent import PPOAgent
  File "E:\LastOrder-Dota2-main\agents\dota_agent.py", line 9, in <module>
    from agents.base_agent import BaseAgent
  File "E:\LastOrder-Dota2-main\agents\base_agent.py", line 10, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by liuhe19940107** [comment]
> PS C:\Users\1060> CD E:\LastOrder-Dota2-main
> PS E:\LastOrder-Dota2-main> python .\play_with_human_local.py
> 2021-08-06 14:30:53.779862: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
> 2021-08-06 14:30:53.780524: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> 2021-08-06 14:30:57,613 WARNING From C:\Users\1060\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Traceback (most recent call last):
> File ".\play_with_human_local.py", line 3, in
> from agents.dota_agent import PPOAgent
> File "E:\LastOrder-Dota2-main\agents\dota_agent.py", line 9, in
> from agents.base_agent import BaseAgent
> File "E:\LastOrder-Dota2-main\agents\base_agent.py", line 10, in
> import psutil
> ModuleNotFoundError: No module named 'psutil'

我的游戏路径不知道对不对，我在dota_game的文件里改了如下
def get_default_game_path():
    game_path = r'C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\bin\win64'
    from play_with_human_local import DOTA_CLINET_PATH_MAC, DOTA_CLINET_PATH_WINDOWS, DOTA_CLINET_PATH_LINUX
    if platform == "linux" or platform == "linux2":
        game_path = os.path.expanduser(os.getenv('DOTA_GAME_PATH', DOTA_CLINET_PATH_LINUX))
    elif platform == 'darwin':
        game_path = os.path.expanduser(
            os.getenv('DOTA_GAME_PATH', DOTA_CLINET_PATH_MAC))
    elif platform == 'win32':
        game_path = os.path.expanduser(
            os.getenv('DOTA_GAME_PATH', DOTA_CLINET_PATH_WINDOWS))

**Comment by Passerby** [comment]
没执行过 pip install -r .\requirements.txt 吧

**Comment by liuhe19940107** [comment]
> 没执行过 pip install -r .\requirements.txt 吧
好的我试试

**Comment by liuhe19940107** [comment]
> 没执行过 pip install -r .\requirements.txt 吧

出现一个新的问题
错误: 没有找到进程 "dota2.exe"。
错误: 没有找到进程 "dota2.exe"。

**Comment by Passerby** [comment]
应该是路径没有填对
